version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  test:
    executor:
      name: win/default
      size: "medium"
    working_directory:  ~/addons-release-tests/

    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run serial tests
          environment:
            MOZ_HEADLESS: 1
          command: pytest -m "serial" --driver Firefox --variables stage.json
          no_output_timeout: 30m
      - run:
          name: Run parallel tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 2
          command: pytest -m "not serial" --driver Firefox --variables stage.json
          no_output_timeout: 30m
      - store_artifacts:
          path: release-test-results.html
      - store_artifacts:
          path: release-test-results.html
workflows:
  commit_workflow:
    jobs:
      - test
  scheduled_stage_release_run:
    triggers:
      - schedule:
          # the workflow runs each Wednesday at 05:00 UTC
          cron: "0 5 * * 3"
          filters:
            branches:
              only: master
    jobs:
      - test
