version: 2.1
orbs:
  win: circleci/windows@2.4.1
jobs:
  # run collections tests in a separate serial job to make serial workflows more granular
  collections_serial_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory:  ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: py -3.9 -m pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: py -3.9 -m pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --version=101.0.1.2022040521-alpha --pre
      - run:
          name: Run collections serial tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 1 --reruns 2
          command: py -3.9 -m pytest tests\frontend\test_collections.py --driver Firefox --variables stage.json --html=collections-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: collections-test-results.html

  # run ratings tests in a separate serial job to make serial workflows more granular
  ratings_serial_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: py -3.9 -m pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: py -3.9 -m pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run ratings serial tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 1 --reruns 2
          command: py -3.9 -m pytest tests\frontend\test_ratings.py --driver Firefox --variables stage.json --html=ratings-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: ratings-test-results.html

  # run user tests in a separate serial job to make serial workflows more granular
  user_serial_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: py -3.9 -m pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: py -3.9 -m pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run user serial tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 1 --reruns 2
          command: py -3.9 -m pytest tests\frontend\test_users.py --driver Firefox --variables stage.json --html=user-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: user-test-results.html

  # tests that do not require login; they include homepage, addon detail, search, addon landing pages, install and other misc tests
  frontend_parallel_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: py -3.9 -m pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: py -3.9 -m pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run frontend parallel tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 4 --reruns 2
          command: py -3.9 -m pytest tests\frontend -m "not serial and not prod_only" --driver Firefox --variables stage.json --html=frontend-parallel-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: frontend-parallel-test-results.html

  # tests that are covering the developer hub homepage
  devhub_parallel_tests:
    executor:
      name: win/default
      version: "previous"
      size: "medium"
    working_directory: ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: py -3.9 -m pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: py -3.9 -m pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run devhub parallel tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 4 --reruns 2
          command: py -3.9 -m pytest tests\devhub\test_devhub_home.py --driver Firefox --variables stage.json --html=devhub-parallel-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: devhub-parallel-test-results.html

  # parallel tests run on production after the AMO push
  sanity_parallel_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: py -3.9 -m pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: py -3.9 -m pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox
      - run:
          name: Sanity parallel tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 4 --reruns 2
          command: py -3.9 -m pytest -m "prod_only or sanity and not serial" --driver Firefox --variables prod.json --html=sanity-parallel-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: sanity-parallel-test-results.html

  # serial tests run on production after the AMO push
  sanity_serial_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: py -3.9 -m pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: py -3.9 -m pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox
      - run:
          name: Sanity serial tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 1 --reruns 2
          command: py -3.9 -m pytest -m "sanity and serial" --driver Firefox --variables prod.json --html=sanity-serial-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: sanity-serial-test-results.html

workflows:
  commit_workflow:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - collections_serial_tests
      - ratings_serial_tests
      - user_serial_tests
      - frontend_parallel_tests
      - devhub_parallel_tests
  # scheduled in CircleCI Project settings to run each Wednesdays at 05:00 UTC
  scheduled_stage_release_run:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "scheduled_stage_release_run", << pipeline.schedule.name >> ]
    jobs:
      - collections_serial_tests
      - ratings_serial_tests
      - user_serial_tests
      - frontend_parallel_tests
      - devhub_parallel_tests
  # scheduled in CircleCI Project settings to start each Thursdays at 17:00 UTC
  scheduled_prod_sanity_run:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "scheduled_prod_sanity_run", << pipeline.schedule.name >> ]
    jobs:
      # this job needs to be Approved in the CircleCI app in order to trigger the next job runs
      # once all the push duty tasks have been completed by AMO ops
      - hold:
          type: approval
      - sanity_parallel_tests: # will run after the hold job is approved
          requires:
            - hold
      - sanity_serial_tests: # # will run after the hold job is approved
          requires:
            - hold
