version: 2.1
orbs:
  win: circleci/windows@2.4.1
jobs:
  # run collections tests in a separate serial job to make serial workflows more granular
  collections_serial_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory:  ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Check installed python verion
          command: python --version
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run collections serial tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 1 --reruns 2
          command: pytest tests\test_collections.py --driver Firefox --variables stage.json --html=collections-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: collections-test-results.html

  # run ratings tests in a separate serial job to make serial workflows more granular
  ratings_serial_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run ratings serial tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 1 --reruns 2
          command: pytest tests\test_ratings.py --driver Firefox --variables stage.json --html=ratings-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: ratings-test-results.html

  # run user tests in a separate serial job to make serial workflows more granular
  user_serial_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run user serial tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 1 --reruns 2
          command: pytest tests\test_users.py --driver Firefox --variables stage.json --html=user-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: user-test-results.html

  # tests that do not require login; they include homepage, addon detail, search, addon landing pages, install and other misc tests
  frontend_parallel_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run frontend parallel tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 4 --reruns 2
          command: pytest -m "not serial" --driver Firefox --variables stage.json --html=frontend-parallel-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: frontend-parallel-test-results.html

  # tests that are covering the developer hub homepage
  devhub_parallel_tests:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/addons-release-tests/
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip --user
      - run:
          name: Install requirements
          command: pip install --no-deps -r ./requirements.txt
      - run:
          name: Install geckodriver
          command: choco install selenium-gecko-driver
      - run:
          name: Install Firefox
          command: choco install firefox-nightly --pre
      - run:
          name: Run devhub parallel tests
          environment:
            MOZ_HEADLESS: 1
            PYTEST_ADDOPTS: -n 4 --reruns 2
          command: pytest tests\test_devhub_home.py --driver Firefox --variables stage.json --html=devhub-parallel-test-results.html --self-contained-html
          no_output_timeout: 30m
      - store_artifacts:
          path: devhub-parallel-test-results.html

workflows:
  commit_workflow:
    jobs:
      - collections_serial_tests
      - ratings_serial_tests
      - user_serial_tests
      - frontend_parallel_tests
      - devhub_parallel_tests
  scheduled_stage_release_run:
    triggers:
      - schedule:
          # the workflow runs each Wednesday at 05:00 UTC
          cron: "0 5 * * 3"
          filters:
            branches:
              only: master
    jobs:
      - collections_serial_tests
      - ratings_serial_tests
      - user_serial_tests
      - frontend_parallel_tests
      - devhub_parallel_tests
